### PR TITLE
Data preservation

### PR DESCRIPTION
**Pull request by MattGomb**
Welcome, Dear Reviewer,

image

In this PR, our hardworking group created the data preservation methods, as per the instructions: 
[OOP school library: preserve data](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_preserve_data.md),

- On exit, all our entered data is saved in the json files
- On load, all our previously entered data is accessible
- All our methods are in separate modules
- All our modules/classes are responsible for only one functionality

P.S.: We got a new teammate on Tuesday, but we cannot reach him, I tried all the official channels, we do not have more time (we are already behind schedule), and he did not make a commit, but we cannot waste time waiting for him. I apologize for this, but please don't hold back our project because of that. Thanks!

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have commits from all partners, please make sure that all partners have balanced commits, this is a team of three, and I can only see   commits from two partners

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DammyShittu** [comment]
Hi @MattGomb and @jfoyarzo,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### There are 3 members in this group but only 2 committed to this project. Kindly ensure the other member contributes to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jfoyarzo** [comment]
Hello @prolajumokeoni and @DammyShittu , thank you for your feedback. I understand the reason for the invalid status but, as stated by Matt on the PR description, we couldn't get a hold of our partner for him to contribute to the project... what are we supposed to do in this case? If our partner Is unresponsive, it will be impossible for him to make commits on this and the upcoming projects. Thanks in advance for your response 😃

**Comment by MattGomb** [comment]
@prolajumokeoni , @DammyShittu  Hey guys,  I wrote to student success, or I made a complaint, i am not sure if I did the right thing, because I never had to do it before, but it is in the works.... Meanwhile we will try to work on the next project

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @jfoyarzo, and @MattGomb👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MattGomb** [comment]
@thecodechaser Thanks!

**Pull request merged**
